#!/bin/bash

if [ -d ./setup.d ]
then
  for FILE in $(find ./setup.d -type f -iname *.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="/usr/bin/env java"

if [ -n "${SERVER_MAXHEAP}" ]
then
  STARTCMD="${STARTCMD} -Xmx${SERVER_MAXHEAP}"
fi

if [ -n "${SERVER_MINHEAP}" ]
then
  STARTCMD="${STARTCMD} -Xms${SERVER_MINHEAP}"
fi


pushd /minecraft > /dev/null
  echo "> starting minecraft service"
  exec ${STARTCMD} ${JAVA_OPTS} -jar ${SERVER_JAR} ${SERVER_OPTS}
popd > /dev/null
